// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseComponent: typeof import('./src/components/BaseComponent.vue')['default']
    BaseContainer: typeof import('./src/components/BaseContainer.vue')['default']
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseLaside: typeof import('./src/components/BaseLaside.vue')['default']
    BaseMain: typeof import('./src/components/BaseMain.vue')['default']
    BaseRaside: typeof import('./src/components/BaseRaside.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CodeEdtior: typeof import('./src/components/CodeEdtior.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColla3pse: typeof import('element-plus/es')['ElColla3pse']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    HCodeEdtior: typeof import('./src/components/HCodeEdtior.vue')['default']
    HDialog: typeof import('./src/components/HDialog.vue')['default']
    HDraggable: typeof import('./src/components/HDraggable.vue')['default']
    HMessage: typeof import('./src/components/HMessage.vue')['default']
    IconDialog: typeof import('./src/components/IconDialog.vue')['default']
    IconsDialog: typeof import('./src/components/IconsDialog.vue')['default']
    InputWidget: typeof import('./src/components/form-widget/InputWidget.vue')['default']
    StructureTree: typeof import('./src/components/StructureTree.vue')['default']
    UnikeyEditor: typeof import('./src/components/form-widget/field-widget/UnikeyEditor.vue')['default']
    UniquekeyEditor: typeof import('./src/components/form-widget/field-widget/UniquekeyEditor.vue')['default']
  }
}

export {}
